-- R.nvim's own ftplugin (r_rnvim.lua, bundled with the plugin) unconditionally
-- probes for the `R` binary on FileType=r via check_nvimcom_version, which
-- throws a hard `jobstart` error instead of failing gracefully when `R` isn't
-- on PATH. R only comes from a per-project direnv here (see
-- lua/user/org_babel.lua), so it's routinely absent. `R_filetypes` is the
-- plugin's own documented knob for which filetypes it should activate on; an
-- empty table (not containing "r") makes its ftplugin bail out before ever
-- reaching that probe.
if vim.fn.executable('R') == 0 then
  vim.g.R_filetypes = {}
end

-- -- Create a table with the options to be passed to setup()
-- local opts = {
--   hook = {
--     on_filetype = function()
--       vim.api.nvim_buf_set_keymap(0, 'n', '<Enter>', '<Plug>RDSendLine', {})
--       vim.api.nvim_buf_set_keymap(0, 'v', '<Enter>', '<Plug>RSendSelection', {})
--     end,
--   },
--   R_args = { '--quiet', '--no-save' },
--   min_editor_width = 72,
--   rconsole_width = 78,
--   objbr_mappings = { -- Object browser keymap
--     c = 'class', -- Call R functions
--     ['<localleader>gg'] = 'head({object}, n = 15)', -- Use {object} notation to write arbitrary R code.
--     v = function()
--       -- Run lua functions
--       require('r.browser').toggle_view()
--     end,
--   },
--   disable_cmds = {
--     'RClearConsole',
--     'RCustomStart',
--     'RSPlot',
--     'RSaveClose',
--   },
-- }
-- -- Check if the environment variable "R_AUTO_START" exists.
-- -- If using fish shell, you could put in your config.fish:
-- -- alias r "R_AUTO_START=true nvim"
-- if vim.env.R_AUTO_START == 'true' then
--   opts.auto_start = 'on startup'
--   opts.objbr_auto_start = true
-- end
-- require('r').setup(opts)
